// ============================================================================
// ATLASBANX — Proph3t benchmark analyst (B3)
// ============================================================================
// Wraps the existing llmEnricher to produce expert-level commentary on the
// tariff benchmark data. Always degrades gracefully to deterministic insights
// when the LLM engine is not connected (Proph3t disabled or offline).
//
// Outputs:
//   • generateExecutiveSummary — 5–8 bullet narrative for the page header
//   • analyzeBenchmarkSection  — per-section commentary (markets, evolution,
//                                zone, drift, compliance, basket, forecast)
//   • answerNaturalLanguageQ   — Q&A on the loaded data
//   • produceFullReportNarrative — paragraph-level prose for the PDF report
// ============================================================================

import type { Bank } from '../types';
import {
  isLlmAvailable,
  llmCall,
  llmCallJson,
} from '../ai/proph3t/intelligence/llmEnricher';
import {
  computeAggressiveness,
  computeCoverage,
  computeCostBasket,
  computeDistribution,
  detectOutliers,
  forecastBank,
  getActiveGrid,
  getNumericValue,
  getZone,
  type AggressivenessScore,
  type BankRubricValue,
  type ClientProfile,
  type RubricRef,
} from './conditionsAnalytics';
import {
  checkCohortCompliance,
  type ComplianceReport,
} from './regulatoryCompliance';

// ───────────────────────────────────────────────────────────────────────────
// EXECUTIVE SUMMARY
// ───────────────────────────────────────────────────────────────────────────

export interface ExecutiveSummary {
  /** 1-line headline (auditor's verdict) */
  headline: string;
  /** Bullet narrative — 5 to 8 items */
  bullets: string[];
  /** Top 3 actionable recommendations */
  recommendations: string[];
  /** Provenance: 'llm' = generated by Proph3t, 'deterministic' = computed locally */
  source: 'llm' | 'deterministic';
}

const SYSTEM_ANALYST = `Tu es un auditeur senior spécialisé en tarification bancaire CEMAC/UEMOA, intervenant pour le compte d'AtlasBanx. Tu rédiges des analyses concises, factuelles, en français, sans superlatifs ni langage commercial. Tu cites toujours les chiffres exacts. Tes conclusions sont actionnables.`;

export async function generateExecutiveSummary(
  banks: Bank[],
  rubrics: RubricRef[],
): Promise<ExecutiveSummary> {
  // Always compute the deterministic version first — used as fallback and
  // also as the data scaffold the LLM commentates on.
  const det = computeDeterministicSummary(banks, rubrics);

  if (!isLlmAvailable()) {
    return { ...det, source: 'deterministic' };
  }

  const userPrompt = buildUserPrompt(banks, rubrics, det);
  const result = await llmCallJson<{
    headline: string;
    bullets: string[];
    recommendations: string[];
  }>(
    SYSTEM_ANALYST + ' Réponds UNIQUEMENT en JSON valide avec les clés "headline" (string), "bullets" (string[]) et "recommendations" (string[]).',
    userPrompt,
    ['headline', 'bullets', 'recommendations'],
    { role: 'fast', temperature: 0.2, maxTokens: 1200 },
  );

  if (!result) return { ...det, source: 'deterministic' };

  return {
    headline: String(result.data.headline || det.headline).slice(0, 240),
    bullets: (Array.isArray(result.data.bullets) ? result.data.bullets : det.bullets)
      .map(String)
      .filter(Boolean)
      .slice(0, 8),
    recommendations: (Array.isArray(result.data.recommendations)
      ? result.data.recommendations
      : det.recommendations)
      .map(String)
      .filter(Boolean)
      .slice(0, 5),
    source: 'llm',
  };
}

function computeDeterministicSummary(
  banks: Bank[],
  rubrics: RubricRef[],
): Omit<ExecutiveSummary, 'source'> {
  const cov = computeCoverage(banks, rubrics);
  const agg = computeAggressiveness(banks, rubrics);
  const compliance = checkCohortCompliance(banks);
  const totalGrids = banks.reduce((s, b) => s + (b.conditionGrids?.length ?? 0), 0);
  const banksWithGrid = banks.filter((b) => (b.conditionGrids?.length ?? 0) > 0).length;

  const mostAggressive = agg.length > 0 ? agg[0] : null;
  const mostCompetitive = agg.length > 0 ? agg[agg.length - 1] : null;
  const worstCompliance = compliance.length > 0 ? compliance[0] : null;

  const bullets: string[] = [];
  bullets.push(
    `Périmètre : ${banksWithGrid}/${banks.length} banques avec grille active, ${totalGrids} version(s) de grille au total, ${rubrics.length} rubriques suivies.`,
  );
  bullets.push(
    `Couverture documentaire : ${(cov.stats.coverageRate * 100).toFixed(0)} % des cellules (banque × rubrique) renseignées.`,
  );
  if (mostAggressive && mostAggressive.n > 0) {
    bullets.push(
      `${mostAggressive.bankName} affiche le profil tarifaire le plus agressif : ${(mostAggressive.aboveQ3Pct * 100).toFixed(0)} % de ses rubriques sont au-dessus du Q3 du marché (échantillon n=${mostAggressive.n}).`,
    );
  }
  if (mostCompetitive && mostCompetitive.n > 0 && mostCompetitive.score < 0) {
    bullets.push(
      `${mostCompetitive.bankName} est globalement en-dessous du marché : ${(mostCompetitive.belowQ1Pct * 100).toFixed(0)} % de ses rubriques sous le Q1.`,
    );
  }
  if (worstCompliance && worstCompliance.violationsCount > 0) {
    bullets.push(
      `Conformité réglementaire : ${worstCompliance.bankName} cumule ${worstCompliance.violationsCount} dépassement(s) (${worstCompliance.criticalCount} critique(s), ${worstCompliance.highCount} sévère(s)) — score ${worstCompliance.score}/100.`,
    );
  }

  // Drift narrative
  const totalDrifts = banks.reduce((sum, b) => {
    const grids = [...(b.conditionGrids ?? [])].sort(
      (a, c) => new Date(a.effectiveDate).getTime() - new Date(c.effectiveDate).getTime(),
    );
    let count = 0;
    for (let i = 1; i < grids.length; i++) {
      for (const r of rubrics) {
        const a = getNumericValue(grids[i - 1], r.path);
        const c = getNumericValue(grids[i], r.path);
        if (a == null || c == null || a === 0) continue;
        if (Math.abs((c - a) / a) >= 0.1) count++;
      }
    }
    return sum + count;
  }, 0);
  if (totalDrifts > 0) {
    bullets.push(
      `Dérives tarifaires détectées : ${totalDrifts} variations >10 % entre versions consécutives sur l'ensemble des grilles.`,
    );
  }

  const recommendations: string[] = [];
  if (mostAggressive && mostAggressive.score > 0.3) {
    recommendations.push(
      `Mettre en surveillance les contrats clients sous ${mostAggressive.bankName} — exposition tarifaire significative (>${(mostAggressive.aboveQ3Pct * 100).toFixed(0)} % de rubriques en haut de marché).`,
    );
  }
  if (worstCompliance && worstCompliance.criticalCount > 0) {
    recommendations.push(
      `Saisir le régulateur : ${worstCompliance.bankName} présente ${worstCompliance.criticalCount} dépassement(s) critique(s) du cadre BCEAO/COBAC. Constituer un dossier de remboursement.`,
    );
  }
  if (cov.stats.coverageRate < 0.6) {
    recommendations.push(
      `Lancer une campagne de relance documentaire — la couverture du benchmark (${(cov.stats.coverageRate * 100).toFixed(0)} %) reste insuffisante pour des conclusions robustes sur certaines rubriques.`,
    );
  }
  if (mostCompetitive && mostCompetitive.score < -0.2) {
    recommendations.push(
      `Utiliser la grille ${mostCompetitive.bankName} comme levier de négociation : son positionnement compétitif sert de référence pour challenger les autres établissements.`,
    );
  }

  let headline = `Audit tarifaire de ${banksWithGrid} banque${banksWithGrid > 1 ? 's' : ''} — ${rubrics.length} rubriques observées.`;
  if (worstCompliance && worstCompliance.criticalCount > 0) {
    headline = `Alerte conformité : ${worstCompliance.criticalCount} dépassement(s) critique(s) BCEAO/COBAC détecté(s).`;
  } else if (totalDrifts > 5) {
    headline = `Marché tarifaire en mouvement : ${totalDrifts} dérives >10 % observées sur la cohorte.`;
  } else if (mostAggressive && mostAggressive.score > 0.4) {
    headline = `${mostAggressive.bankName} se distingue comme l'acteur le plus cher de l'échantillon.`;
  }

  return {
    headline,
    bullets,
    recommendations,
  };
}

function buildUserPrompt(
  banks: Bank[],
  rubrics: RubricRef[],
  det: Omit<ExecutiveSummary, 'source'>,
): string {
  const cov = computeCoverage(banks, rubrics);
  const agg = computeAggressiveness(banks, rubrics).slice(0, 5);
  const compliance = checkCohortCompliance(banks).slice(0, 5);

  // Sample distributions for a few key rubriques
  const keyRubrics = rubrics
    .filter((r) =>
      [
        'accountFees.tenueCompte.particulier',
        'creditFees.tauxDecouvertAutorise',
        'creditFees.tauxUsureLegal',
        'cardFees.visaClassic',
      ].includes(r.path),
    );
  const distSnippets = keyRubrics
    .map((r) => {
      const samples: BankRubricValue[] = [];
      for (const b of banks) {
        const grid = getActiveGrid(b);
        if (!grid) continue;
        const v = getNumericValue(grid, r.path);
        if (v == null || v === 0) continue;
        samples.push({
          bankId: b.id,
          bankCode: b.code,
          bankName: b.name,
          zone: getZone(b),
          value: v,
        });
      }
      const dist = computeDistribution(samples.map((s) => s.value));
      if (!dist) return null;
      return `- ${r.label} (${r.unit}) — n=${dist.n}, médiane=${dist.median.toFixed(2)}, Q1=${dist.q1.toFixed(2)}, Q3=${dist.q3.toFixed(2)}, min=${dist.min.toFixed(2)}, max=${dist.max.toFixed(2)}`;
    })
    .filter(Boolean)
    .join('\n');

  return `Données du benchmark tarifaire :

== Périmètre ==
${banks.length} banques, ${rubrics.length} rubriques, couverture ${(cov.stats.coverageRate * 100).toFixed(0)} %.

== Profil d'agressivité (top 5) ==
${agg
  .map(
    (a, i) =>
      `${i + 1}. ${a.bankName} — score ${a.score.toFixed(2)} (au-dessus du Q3 sur ${(a.aboveQ3Pct * 100).toFixed(0)} % des rubriques, en-dessous du Q1 sur ${(a.belowQ1Pct * 100).toFixed(0)} %).`,
  )
  .join('\n')}

== Conformité BCEAO/COBAC (top 5 worst) ==
${compliance
  .map(
    (c, i) =>
      `${i + 1}. ${c.bankName} — score ${c.score}/100 — ${c.violationsCount} violation(s) (${c.criticalCount} critique(s), ${c.highCount} sévère(s)).`,
  )
  .join('\n')}

== Distributions clés ==
${distSnippets || '(données insuffisantes)'}

== Synthèse déterministe (référence) ==
Headline : ${det.headline}
${det.bullets.map((b) => '• ' + b).join('\n')}

Tâche : produit une synthèse exécutive structurée pour ce benchmark. La synthèse doit être incisive, factuelle, et orientée action pour un cabinet d'audit. 5 à 7 bullets maximum, 3 recommandations actionnables. Utilise des chiffres exacts.`;
}

// ───────────────────────────────────────────────────────────────────────────
// PER-SECTION INSIGHTS
// ───────────────────────────────────────────────────────────────────────────

export type SectionId = 'benchmark' | 'evolution' | 'zone' | 'drift' | 'compliance' | 'basket' | 'forecast';

export interface SectionInsight {
  /** 2–4 paragraphs of expert commentary */
  paragraphs: string[];
  /** Numbered list of concrete actions */
  actions: string[];
  source: 'llm' | 'deterministic';
}

export async function analyzeBenchmarkSection(
  section: SectionId,
  banks: Bank[],
  rubrics: RubricRef[],
  context?: { profile?: ClientProfile; focusBankId?: string },
): Promise<SectionInsight> {
  const det = computeSectionInsightDeterministic(section, banks, rubrics, context);
  if (!isLlmAvailable()) return { ...det, source: 'deterministic' };

  const result = await llmCall(
    SYSTEM_ANALYST + ' Réponds en JSON {"paragraphs": string[], "actions": string[]}.',
    buildSectionPrompt(section, banks, rubrics, det, context),
    { role: 'fast', temperature: 0.25, maxTokens: 900, jsonMode: true },
  );
  if (!result) return { ...det, source: 'deterministic' };

  try {
    const parsed = JSON.parse(result.content);
    return {
      paragraphs: Array.isArray(parsed.paragraphs) ? parsed.paragraphs.map(String) : det.paragraphs,
      actions: Array.isArray(parsed.actions) ? parsed.actions.map(String) : det.actions,
      source: 'llm',
    };
  } catch {
    return { ...det, source: 'deterministic' };
  }
}

function computeSectionInsightDeterministic(
  section: SectionId,
  banks: Bank[],
  rubrics: RubricRef[],
  context?: { profile?: ClientProfile; focusBankId?: string },
): Omit<SectionInsight, 'source'> {
  switch (section) {
    case 'benchmark': {
      const agg = computeAggressiveness(banks, rubrics);
      const top = agg.slice(0, 3);
      return {
        paragraphs: [
          `La cohorte rassemble ${banks.length} banques sur ${rubrics.length} rubriques tarifaires. Le profil d'agressivité — calculé comme le pourcentage de rubriques où la banque dépasse le 3e quartile — situe ${top[0]?.bankName ?? '—'} en tête (${((top[0]?.aboveQ3Pct ?? 0) * 100).toFixed(0)} %).`,
          `À l'opposé du spectre, ${agg[agg.length - 1]?.bankName ?? '—'} se positionne sous le 1er quartile sur ${((agg[agg.length - 1]?.belowQ1Pct ?? 0) * 100).toFixed(0)} % des rubriques observées, ce qui en fait un benchmark de référence pour challenger les autres établissements.`,
        ],
        actions: top.slice(0, 3).map((a, i) => `${i + 1}. Documenter la position tarifaire de ${a.bankName} (score ${a.score.toFixed(2)}) dans les revues de portefeuille client.`),
      };
    }
    case 'evolution': {
      const focusBank = banks.find((b) => b.id === context?.focusBankId) ?? banks[0];
      const grids = focusBank ? focusBank.conditionGrids ?? [] : [];
      return {
        paragraphs: [
          `${focusBank?.name ?? 'Cette banque'} a publié ${grids.length} version${grids.length > 1 ? 's' : ''} de grille tarifaire. L'analyse chronologique permet de distinguer les rubriques structurellement stables de celles soumises à une dérive haussière régulière.`,
          `Une variation supérieure à 10 % entre deux versions consécutives mérite d'être interrogée : alignement réglementaire ? Ajustement à l'inflation ? Refonte commerciale ? Le détail par rubrique permet de qualifier la nature du mouvement.`,
        ],
        actions: [
          '1. Recouper chaque variation >10 % avec la communication officielle de la banque.',
          '2. Identifier les rubriques qui dérivent simultanément (signal d\'une refonte tarifaire globale).',
          '3. Notifier les clients impactés par les hausses les plus significatives.',
        ],
      };
    }
    case 'zone': {
      return {
        paragraphs: [
          `La parité fixe entre XAF et XOF rend les comparaisons CEMAC ↔ UEMOA directement exploitables sur les frais en monnaie. Les écarts de médiane traduisent des positionnements concurrentiels et réglementaires distincts entre les deux zones.`,
          `Un écart >10 % sur une rubrique standardisée (taux usure, tenue de compte) suggère soit une différence de cadre réglementaire (BCEAO vs COBAC), soit une intensité concurrentielle hétérogène. Les agios et taux d'usure sont les rubriques les plus sensibles à différencier.`,
        ],
        actions: [
          '1. Identifier les rubriques où l\'écart inter-zones dépasse 15 % (signal d\'arbitrage).',
          '2. Confronter ces écarts au texte réglementaire pour distinguer ce qui relève du cadre L1 versus du marché.',
          '3. Construire un argumentaire d\'opportunité pour les clients pouvant déplacer leur activité entre zones.',
        ],
      };
    }
    case 'drift': {
      return {
        paragraphs: [
          `Les dérives tarifaires sont le signal faible d'un changement de stratégie commerciale. Une banque qui augmente brutalement de >30 % sur une rubrique a soit alignement réglementaire, soit recherche de marge, soit transfert de coût d'une rubrique à une autre.`,
          `Les dérives critiques (>100 %) dénotent un repositionnement majeur — souvent l'apparition d'un nouveau service ou la suppression d'une gratuité historique. Elles méritent une investigation systématique.`,
        ],
        actions: [
          '1. Pour chaque dérive critique, vérifier que la banque a notifié ses clients dans le délai réglementaire (préavis de 60 jours en UEMOA).',
          '2. Cartographier les dérives par catégorie pour détecter les déplacements de marge (baisse sur cartes → hausse sur agios).',
          '3. Constituer une note de sensibilisation client pour les dérives haussières >30 %.',
        ],
      };
    }
    case 'compliance': {
      const reps = checkCohortCompliance(banks);
      const totalCritical = reps.reduce((s, r) => s + r.criticalCount, 0);
      return {
        paragraphs: [
          `Le contrôle de conformité confronte chaque grille active aux plafonds BCEAO et COBAC d'ordre public. La cohorte présente ${totalCritical} dépassement(s) critique(s).`,
          `Un dépassement critique (taux d'usure, plafond CCM) constitue une infraction au cadre L1 : il ouvre droit à restitution pour les clients concernés et peut faire l'objet d'une saisine du régulateur.`,
        ],
        actions: reps
          .filter((r) => r.criticalCount > 0)
          .slice(0, 3)
          .map(
            (r, i) =>
              `${i + 1}. ${r.bankName} : constituer un dossier de restitution sur les ${r.criticalCount} infraction(s) critique(s) — voir références BCEAO/COBAC dans la liste détaillée.`,
          ),
      };
    }
    case 'basket': {
      const profile = context?.profile ?? 'particulier_basique';
      const baskets = computeCostBasket(banks, profile);
      const cheapest = baskets[0];
      const dearest = baskets[baskets.length - 1];
      const spread = cheapest && dearest ? dearest.totalAnnual - cheapest.totalAnnual : 0;
      return {
        paragraphs: [
          `Le panier ${profile} génère un coût annuel allant de ${cheapest?.totalAnnual.toLocaleString('fr-FR') ?? '—'} XAF (${cheapest?.bankName ?? '—'}) à ${dearest?.totalAnnual.toLocaleString('fr-FR') ?? '—'} XAF (${dearest?.bankName ?? '—'}). L'écart absolu est de ${spread.toLocaleString('fr-FR')} XAF/an.`,
          `Cette comparaison ne reflète qu'un profil-type. Le coût réel pour un client donné dépend de son volume de transactions effectif. Néanmoins, l'écart factuel matérialise l'enjeu de la négociation tarifaire.`,
        ],
        actions: [
          `1. Présenter ce panier-type au client lors des revues annuelles de relation bancaire.`,
          `2. Adapter le panier au profil réel du client (volumes de virements, retraits, etc.).`,
          `3. Utiliser ${cheapest?.bankName ?? 'la banque la moins chère'} comme référence dans les négociations.`,
        ],
      };
    }
    case 'forecast': {
      const focusBank = banks.find((b) => b.id === context?.focusBankId) ?? banks[0];
      const forecasts = focusBank ? forecastBank(focusBank, rubrics) : [];
      const rising = forecasts.filter((f) => f.cagrPct != null && f.cagrPct > 5).slice(0, 3);
      return {
        paragraphs: [
          `${focusBank?.name ?? 'Cette banque'} présente ${forecasts.length} rubriques avec assez d'historique pour une projection. ${rising.length} rubrique(s) montrent un taux de croissance annuel composé supérieur à 5 %.`,
          `Les projections sont des extrapolations linéaires : elles supposent la continuité du pattern observé. Tout choc réglementaire ou stratégique invaliderait ces estimations. À utiliser comme signal de surveillance, pas comme prévision contractuelle.`,
        ],
        actions: rising.map(
          (f, i) =>
            `${i + 1}. Surveiller ${f.rubricLabel} — projection à 12 mois : ${f.forecast12m?.toLocaleString('fr-FR') ?? '—'} (CAGR ${f.cagrPct?.toFixed(1) ?? '—'} %).`,
        ),
      };
    }
  }
}

function buildSectionPrompt(
  section: SectionId,
  banks: Bank[],
  rubrics: RubricRef[],
  det: Omit<SectionInsight, 'source'>,
  context?: { profile?: ClientProfile; focusBankId?: string },
): string {
  return `Section : ${section}.
Périmètre : ${banks.length} banques, ${rubrics.length} rubriques.
${context?.focusBankId ? `Banque focus : ${banks.find((b) => b.id === context.focusBankId)?.name ?? 'inconnue'}.` : ''}
${context?.profile ? `Profil client : ${context.profile}.` : ''}

Synthèse déterministe (référence) :
${det.paragraphs.map((p, i) => `(${i + 1}) ${p}`).join('\n')}

Actions déterministes :
${det.actions.join('\n')}

Tâche : reformule cette analyse pour qu'elle soit plus incisive et nuancée. 2 à 4 paragraphes courts, 3 actions numérotées. Garde les chiffres exacts. Pas de superlatifs.`;
}

// ───────────────────────────────────────────────────────────────────────────
// NATURAL LANGUAGE Q&A
// ───────────────────────────────────────────────────────────────────────────

export interface NlqAnswer {
  answer: string;
  source: 'llm' | 'deterministic';
  /** Citations / data points used */
  citations: string[];
}

export async function answerNaturalLanguageQ(
  question: string,
  banks: Bank[],
  rubrics: RubricRef[],
): Promise<NlqAnswer> {
  // Build a compact data digest the LLM can cite from
  const digest = buildDataDigest(banks, rubrics);

  if (!isLlmAvailable()) {
    return {
      answer:
        'Le moteur d\'analyse Proph3t n\'est pas connecté. Active une instance Ollama dans Paramètres → Intelligence pour activer les requêtes en langage naturel. ' +
        'En attendant, utilise les sections Benchmark, Évolution, CEMAC vs UEMOA, Conformité et Dérives pour explorer la donnée.',
      source: 'deterministic',
      citations: [],
    };
  }

  const result = await llmCall(
    SYSTEM_ANALYST + ' Tu réponds aux questions sur les données du benchmark fournies. Cite toujours les chiffres exacts. Si la donnée manque, dis-le explicitement plutôt que de spéculer.',
    `${digest}\n\nQuestion : ${question}\n\nRéponds en français, 4 lignes maximum, en citant les chiffres pertinents.`,
    { role: 'fast', temperature: 0.2, maxTokens: 600 },
  );

  if (!result) {
    return {
      answer: 'Le moteur Proph3t a échoué à répondre. Réessaye dans un instant ou consulte les sections détaillées du module.',
      source: 'deterministic',
      citations: [],
    };
  }

  return {
    answer: result.content.trim(),
    source: 'llm',
    citations: digest.split('\n').filter((l) => l.startsWith('•')),
  };
}

function buildDataDigest(banks: Bank[], rubrics: RubricRef[]): string {
  const lines: string[] = ['== Digest du benchmark ==', `${banks.length} banques, ${rubrics.length} rubriques.`];
  for (const b of banks) {
    const grid = getActiveGrid(b);
    if (!grid) continue;
    lines.push(`• ${b.name} (${b.code}, ${getZone(b) ?? 'zone inconnue'}) — grille ${grid.name} (effective ${formatDate(grid.effectiveDate)}).`);
    for (const r of rubrics.slice(0, 12)) {
      const v = getNumericValue(grid, r.path);
      if (v == null || v === 0) continue;
      lines.push(`    - ${r.label} : ${v} ${r.unit}`);
    }
  }
  // Add aggregates
  const agg = computeAggressiveness(banks, rubrics).slice(0, 3);
  lines.push('== Top 3 banques agressives ==');
  agg.forEach((a) => {
    lines.push(`• ${a.bankName} — score ${a.score.toFixed(2)}, Q3+ sur ${(a.aboveQ3Pct * 100).toFixed(0)} %.`);
  });
  return lines.join('\n');
}

function formatDate(d: Date | string): string {
  const dt = typeof d === 'string' ? new Date(d) : d;
  return dt.toLocaleDateString('fr-FR');
}

// ───────────────────────────────────────────────────────────────────────────
// FULL REPORT NARRATIVE (used by BenchmarkReportService)
// ───────────────────────────────────────────────────────────────────────────

export interface ReportNarrative {
  cover: { subtitle: string };
  executiveSummary: ExecutiveSummary;
  sectionInsights: Record<SectionId, SectionInsight>;
  source: 'llm' | 'deterministic' | 'mixed';
}

export async function produceFullReportNarrative(
  banks: Bank[],
  rubrics: RubricRef[],
  context?: { profile?: ClientProfile; focusBankId?: string },
): Promise<ReportNarrative> {
  const sections: SectionId[] = ['benchmark', 'evolution', 'zone', 'drift', 'compliance', 'basket', 'forecast'];

  const exec = await generateExecutiveSummary(banks, rubrics);
  const sectionResults = await Promise.all(
    sections.map((s) => analyzeBenchmarkSection(s, banks, rubrics, context)),
  );

  const sectionInsights: Record<string, SectionInsight> = {};
  sections.forEach((s, i) => {
    sectionInsights[s] = sectionResults[i];
  });

  const llmCount = [exec.source === 'llm', ...sectionResults.map((r) => r.source === 'llm')].filter(Boolean).length;
  const source: ReportNarrative['source'] =
    llmCount === sections.length + 1 ? 'llm'
    : llmCount === 0 ? 'deterministic'
    : 'mixed';

  return {
    cover: {
      subtitle: exec.headline,
    },
    executiveSummary: exec,
    sectionInsights: sectionInsights as Record<SectionId, SectionInsight>,
    source,
  };
}

// Re-export so consumers can also probe the engine status
export { isLlmAvailable } from '../ai/proph3t/intelligence/llmEnricher';

/** Simplified report-level summary of the cohort compliance, useful for the PDF. */
export function summarizeCompliance(banks: Bank[]): {
  overallScore: number;
  total: number;
  perfect: number;
  withCritical: number;
  worstReport: ComplianceReport | null;
} {
  const reps = checkCohortCompliance(banks);
  const overall = reps.length === 0 ? 100 : reps.reduce((s, r) => s + r.score, 0) / reps.length;
  return {
    overallScore: Math.round(overall),
    total: reps.length,
    perfect: reps.filter((r) => r.score === 100).length,
    withCritical: reps.filter((r) => r.criticalCount > 0).length,
    worstReport: reps[0] ?? null,
  };
}
